on:
  push:
    branches:
      - "develop"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.USERNAME }}/gocrud2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.4

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch required Go modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run functional tests
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
